# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 600)
        # 使用setFixedSize方法限制窗口大小
        MainWindow.setFixedSize(900, 600)  # 限制宽度为400像素，高度为300像素
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.vediolabel = QtWidgets.QLabel(self.centralwidget)
        self.vediolabel.setGeometry(QtCore.QRect(50, 50, 600, 480))
        self.vediolabel.setObjectName("vediolabel")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(680, 160, 201, 81))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sum = QtWidgets.QLabel(self.layoutWidget)
        self.sum.setObjectName("sum")
        self.horizontalLayout.addWidget(self.sum)
        self.total = QtWidgets.QLabel(self.layoutWidget)
        self.total.setObjectName("total")
        self.horizontalLayout.addWidget(self.total)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(680, 250, 201, 71))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.sum_s = QtWidgets.QLabel(self.layoutWidget1)
        self.sum_s.setObjectName("sum_s")
        self.horizontalLayout_2.addWidget(self.sum_s)
        self.s = QtWidgets.QLabel(self.layoutWidget1)
        self.s.setObjectName("s")
        self.horizontalLayout_2.addWidget(self.s)
        self.start = QtWidgets.QPushButton(self.centralwidget)
        self.start.setGeometry(QtCore.QRect(730, 380, 93, 28))
        self.start.setObjectName("start")
        self.time = QtWidgets.QLabel(self.centralwidget)
        self.time.setGeometry(QtCore.QRect(710, 50, 141, 101))
        font = QtGui.QFont()
        font.setPointSize(50)
        self.time.setFont(font)
        self.time.setObjectName("time")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        #创建槽函数
        self.start.clicked.connect(self.onButtonClicked)
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.vediolabel.setText(_translate("MainWindow", "TextLabel"))
        self.sum.setText(_translate("MainWindow", "总个数"))
        self.total.setText(_translate("MainWindow", "TextLabel"))
        self.sum_s.setText(_translate("MainWindow", "总得分"))
        self.s.setText(_translate("MainWindow", "TextLabel"))
        self.start.setText(_translate("MainWindow", "开始"))
        self.time.setText(_translate("MainWindow", "2"))
